" Colorscheme generated by https://github.com/arcticlimer/djanho

highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = (a:bg == '' || a:bg == 'NONE') ? 'guibg=NONE' : 'guibg=' . a:bg
  let fg = fg == '' ? '' : fg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg . ' ' . gui
endfunction


let s:Color3 = '#C792EA'
let s:Color16 = '#848484'
let s:Color1 = '#EEFFFF'
let s:Color6 = '#F78C6C'
let s:Color7 = '#C3E88D'
let s:Color13 = '#3c272a'
let s:Color8 = '#616161'
let s:Color4 = '#89DDFF'
let s:Color12 = '#2e3129'
let s:Color14 = '#353535'
let s:Color17 = '#ffffff'
let s:Color5 = '#82AAFF'
let s:Color9 = '#1a1a1a'
let s:Color10 = '#eeffff'
let s:Color15 = '#424242'
let s:Color11 = '#212121'
let s:Color0 = '#4A4A4A'
let s:Color2 = '#FF5370'
let s:ErrorCol = '#FF5370'
let s:Prop = '#f07178'

call s:highlight('Comment', '', s:Color0, 'italic')
call s:highlight('Identifier', '', s:Color1, '')
call s:highlight('Error', '', s:Color2, '')
call s:highlight('Keyword', '', s:Color4, '')
call s:highlight('Conditional', '', s:Color4, '')
call s:highlight('Repeat', '', s:Color4, '')
call s:highlight('Conditional', '', '', 'italic')
call s:highlight('Repeat', '', '', 'italic')
call s:highlight('Function', '', s:Color5, '')
call s:highlight('Number', '', s:Color6, '')
call s:highlight('TSCharacter', '', s:Color6, '')
call s:highlight('String', '', s:Color7, '')
call s:highlight('StatusLine', s:Color8, s:Color9, '')
call s:highlight('WildMenu', s:Color11, s:Color10, '')
call s:highlight('Pmenu', s:Color11, s:Color10, '')
call s:highlight('PmenuSel', s:Color10, '', '')
call s:highlight('PmenuThumb', s:Color11, s:Color10, '')
call s:highlight('DiffAdd', s:Color12, '', '')
call s:highlight('DiffDelete', s:Color13, '', '')
call s:highlight('Normal', s:Color11, s:Color10, '')
call s:highlight('Visual', s:Color14, '', '')
call s:highlight('CursorLine', s:Color14, '', '')
call s:highlight('ColorColumn', s:Color14, '', '')
call s:highlight('SignColumn', s:Color11, '', '')
call s:highlight('LineNr', '', s:Color15, '')
call s:highlight('TabLine', s:Color11, s:Color16, '')
call s:highlight('TabLineSel', s:Color17, '', '')
call s:highlight('TabLineFill', s:Color11, s:Color16, '')
call s:highlight('TSPunctDelimiter', '', s:Color10, '')

" Transparency
call s:highlight('Normal', 'NONE', s:Color10, '')
call s:highlight('NormalNC', 'NONE', s:Color10, '')
call s:highlight('SignColumn', 'NONE', s:Color11, '')
call s:highlight('VertSplit', 'NONE', s:Color15, '')
call s:highlight('StatusLine', 'NONE', s:Color9, '')
call s:highlight('LineNr', 'NONE', s:Color15, '')
call s:highlight('CursorLine', 'NONE', '', '')
call s:highlight('ColorColumn', 'NONE', '', '')

" Core groups
hi Normal       guibg=NONE
hi NormalNC     guibg=NONE
hi SignColumn   guibg=NONE
hi VertSplit    guibg=NONE
hi StatusLine   guibg=NONE
hi LineNr       guibg=NONE
hi CursorLine   guibg=NONE
hi ColorColumn  guibg=NONE

" Floating windows / popup menus
hi Pmenu        guibg=NONE
hi PmenuSel     guibg=NONE
hi PmenuThumb   guibg=NONE
hi FloatBorder  guibg=NONE
hi NormalFloat  guibg=NONE


" Telescope (if you use it)
hi TelescopeNormal   guibg=NONE
hi TelescopeBorder   guibg=NONE
hi TelescopePromptNormal guibg=NONE
hi TelescopePromptBorder guibg=NONE
hi TelescopePromptTitle guibg=NONE
hi TelescopePreviewTitle guibg=NONE
hi TelescopeResultsTitle guibg=NONE



highlight! link TSPunctBracket MyTag
highlight! link TSFunction Function
highlight! link Macro Function
highlight! link TSParameterReference TSParameter
highlight! link Whitespace Comment
highlight! link Folded Comment
highlight! link CursorLineNr Identifier
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link TSConstant Constant
highlight! link TSComment Comment
highlight! link NonText Comment
highlight! link TSString String
highlight! link TSRepeat Repeat
highlight! link Conditional Operator
highlight! link TSLabel Type
highlight! link TSOperator Operator
highlight! link TSKeyword Keyword
highlight! link TelescopeNormal Normal
highlight! link TSConditional Conditional
highlight! link TSFuncMacro Macro
highlight! link TSFloat Number
highlight! link TSTagDelimiter Type
highlight! link TSType Type
highlight! link TSNamespace TSType
highlight! link TSField Constant
highlight! link TSNumber Number
highlight! link TSTag MyTag
highlight! link Operator Keyword
highlight! link TSParameter Constant
highlight! link Repeat Conditional
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link TSProperty TSField
highlight! link TSStatement Conditional

" Custom highlight for import keyword
call s:highlight('TSKeywordDeclaration', '', '#C792EA', '')

" Link Treesitter capture for imports to this group
highlight! link @keyword. TSKeywordDeclaration


" Keywords
call s:highlight('@keyword', '', '#C792EA', '')
call s:highlight('@keyword.function', '', '#C792EA', 'italic')
call s:highlight('@keyword.operator', '', '#C792EA', '')
call s:highlight('@keyword.import', '', '#89DDFF', '')
call s:highlight('@keyword.export', '', '#89DDFF', '')
call s:highlight('@keyword.switch', '', '#89DDFF', '')
call s:highlight('@keyword.coroutine', '', '#89DDFF', '')



" Variables
call s:highlight('@variable.member', '', '#EEFFFF', '')
call s:highlight('@variable.builtin', '', s:Color6, '')
call s:highlight('@lsp.typemod.variable.declaration', '', s:Prop, '')
call s:highlight('@lsp.typemod.parameter.declaration', '', s:Prop, '')

call s:highlight('@variable.import', '', '#FF5370', '')
call s:highlight('@variable', '', '#EEFFFF', '')

call s:highlight('LscReferenceText', '', '#EEFFFF', '')


" Functions
call s:highlight('@function', '', '#82AAFF', '')
call s:highlight('@function.builtin', '', '#82AAFF', '')
call s:highlight('@method', '', '#82AAFF', 'italic')
call s:highlight('@method.call', '', '#82AAFF', '')
call s:highlight('@constructor', '', '#82AAFF', '')

" Constants & Numbers
call s:highlight('@constant', '', s:Color6, '')
call s:highlight('@constant.builtin', '', s:Color6, '')
call s:highlight('@constant.macro', '', s:Color6, '')
call s:highlight('@number', '', s:Color6, '')

" Strings
call s:highlight('@string', '', '#C3E88D', '')
call s:highlight('@string.regex', '', '#89DDFF', '')
call s:highlight('@string.escape', '', '#89DDFF', '')

" Types & Classes
call s:highlight('@type', '', '#FFCB6B', '')
call s:highlight('@type.builtin', '', '#B2CCD6', '')
call s:highlight('@class', '', '#FFCB6B', '')
call s:highlight('@interface', '', '#FFCB6B', '')
call s:highlight('@namespace', '', '#FFCB6B', '')

" Comments
call s:highlight('@comment', '', '#4A4A4A', 'italic')

" Diagnostics
call s:highlight('DiagnosticUnnecessary', '', s:Color16, 'italic')
call s:highlight('DiagnosticHint', '', s:Color16, 'italic')
call s:highlight('DiagnosticError', '', s:ErrorCol, 'italic')
call s:highlight('DiagnosticInfo', '', s:ErrorCol, 'italic')


" Decorators
call s:highlight('@decorator', '', '#82AAFF', 'italic')

" Punctuation
call s:highlight('@punctuation', '', '#89DDFF', '')

" Boolean / Null
call s:highlight('@boolean', '', '#F78C6C', '')
call s:highlight('@null', '', '#F78C6C', '')

" Tags (JSX/HTML)
call s:highlight('@tag', '', '#f07178', '')
call s:highlight('@tag.attribute', '', '#C792EA', 'italic')
call s:highlight('@tag.delimiter', '', '#89DDFF', '')

" Property / Field
" call s:highlight('@property', '', '#f07178', '')
" call s:highlight('@field', '', '#f07178', '')

" Constants / Symbols
call s:highlight('@symbol', '', '#C3E88D', '')
call s:highlight('@constant.symbol', '', '#C3E88D', '')

" Parameters
" call s:highlight('@parameter', '', '#FF5370', '')
" call s:highlight('@parameter.reference', '', '#FF5370', '')

" Conditional / Loops
call s:highlight('@conditional', '', '#89DDFF', '')
call s:highlight('@repeat', '', '#89DDFF', '')
call s:highlight('@boolean', '', '#F78C6C', '')

" JSON Specific
call s:highlight('@property.json', '', '#C792EA', '')
call s:highlight('@property.jsonc', '', '#C792EA', '')


